# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

ArtworkShare.delete_all
Artwork.delete_all
User.delete_all

User.create([{
    username: "hverty0"
  }, {
    username: "msamudio1"
  }, {
    username: "iparrington2"
  }, {
    username: "jvowles3"
  }, {
    username: "hgatch4"
  }, {
    username: "rbeckmann5"
  }, {
    username: "lmanchester6"
  }, {
    username: "skeedy7"
}])

Artwork.create([{
    title: "Hartweg's Twinevine",
    image_url: "exblog.jp/tempor/turpis/nec.json",
    artist_id: 1
  }, {
    title: "Graves' Plum",
    image_url: "amazonaws.com/egestas/metus/aenean/fermentum/donec/ut.jsp",
    artist_id: 5
  }, {
    title: "Rough Eyelashweed",
    image_url: "free.fr/turpis/sed/ante/vivamus/tortor/duis/mattis.aspx",
    artist_id: 8
  }, {
    title: "Sparselobe Grapefern",
    image_url: "plala.or.jp/pede/malesuada.jsp",
    artist_id: 2
  }, {
    title: "Sisal Hemp",
    image_url: "wired.com/integer/aliquet/massa/id.png",
    artist_id: 3
  }, {
    title: "Bryocrumia Moss",
    image_url: "ucsd.edu/vitae/nisl/aenean.js",
    artist_id: 7
  }, {
    title: "Torenia",
    image_url: "nature.com/nam/ultrices/libero/non.json",
    artist_id: 4
  }, {
    title: "Fringed Linanthus",
    image_url: "ameblo.jp/orci/luctus/et/ultrices/posuere/cubilia/curae.png",
    artist_id: 8
  }, {
    title: "Cyrtandra",
    image_url: "oakley.com/eros/suspendisse/accumsan/tortor/quis.js",
    artist_id: 6
  }, {
    title: "Purple Sand Verbena",
    image_url: "altervista.org/ut/erat/curabitur/gravida/nisi.json",
    artist_id: 6
  }, {
    title: "Sedge",
    image_url: "t.co/nulla.xml",
    artist_id: 2
  }, {
    title: "Dwarf Clover",
    image_url: "google.de/mauris/lacinia/sapien.jsp",
    artist_id: 4
  }, {
    title: "Falcaria",
    image_url: "yelp.com/molestie/nibh/in/lectus/pellentesque.html",
    artist_id: 8
  }, {
    title: "Epipterygium Moss",
    image_url: "acquirethisname.com/sed/tristique/in/tempus/sit/amet/sem.jpg",
    artist_id: 1
  }, {
    title: "West Indian Livingvase",
    image_url: "prnewswire.com/posuere/metus/vitae/ipsum/aliquam/non.js",
    artist_id: 2
  }, {
    title: "Chaplin's Golden Columbine",
    image_url: "tmall.com/vel/dapibus/at.aspx",
    artist_id: 2
  }, {
    title: "Birch",
    image_url: "technorati.com/in.js",
    artist_id: 5
  }, {
    title: "Carolina Crabgrass",
    image_url: "amazon.co.uk/integer/ac/neque/duis/bibendum/morbi.jsp",
    artist_id: 4
  }, {
    title: "Desmatodon Moss",
    image_url: "economist.com/ut/erat/id.json",
    artist_id: 3
  }, {
    title: "Big Carpetgrass",
    image_url: "vkontakte.ru/tempus/semper/est/quam/pharetra/magna.xml",
    artist_id: 7
  }, {
    title: "Southern Bayberry",
    image_url: "discovery.com/donec/vitae/nisi/nam/ultrices/libero.png",
    artist_id: 4
  }, {
    title: "Froelich's Dung Moss",
    image_url: "upenn.edu/ipsum/primis.png",
    artist_id: 8
  }, {
    title: "Fries' Pussytoes",
    image_url: "alexa.com/id/pretium/iaculis/diam/erat/fermentum/justo.png",
    artist_id: 3
  }, {
    title: "Pineland Milkpea",
    image_url: "who.int/enim/lorem.aspx",
    artist_id: 2
  }, {
    title: "Elizabeth's Felt Lichen",
    image_url: "ftc.gov/congue/diam/id/ornare/imperdiet/sapien/urna.png",
    artist_id: 3
  }, {
    title: "Garland-lily",
    image_url: "jalbum.net/pretium/iaculis/justo/in.jsp",
    artist_id: 1
  }, {
    title: "Pylaes' Sphagnum",
    image_url: "nasa.gov/nam/dui.xml",
    artist_id: 1
  }, {
    title: "Red Wattle",
    image_url: "wp.com/eu/sapien/cursus/vestibulum/proin/eu/mi.xml",
    artist_id: 5
  }, {
    title: "Gulf Coast Lupine",
    image_url: "google.cn/posuere/cubilia/curae/mauris.html",
    artist_id: 2
  }, {
    title: "Krapovickasia",
    image_url: "umich.edu/sapien.jpg",
    artist_id: 8
}])

ArtworkShare.create([{
    artwork_id: 9,
    viewer_id: 7
  }, {
    artwork_id: 5,
    viewer_id: 6
  }, {
    artwork_id: 17,
    viewer_id: 1
  }, {
    artwork_id: 6,
    viewer_id: 8
  }, {
    artwork_id: 17,
    viewer_id: 5
  }, {
    artwork_id: 7,
    viewer_id: 5
  }, {
    artwork_id: 13,
    viewer_id: 4
  }, {
    artwork_id: 13,
    viewer_id: 1
  }, {
    artwork_id: 2,
    viewer_id: 4
  }, {
    artwork_id: 17,
    viewer_id: 6
  }, {
    artwork_id: 11,
    viewer_id: 1
  }, {
    artwork_id: 26,
    viewer_id: 6
  }, {
    artwork_id: 22,
    viewer_id: 3
  }, {
    artwork_id: 8,
    viewer_id: 7
  }, {
    artwork_id: 28,
    viewer_id: 2
  }, {
    artwork_id: 3,
    viewer_id: 3
  }, {
    artwork_id: 18,
    viewer_id: 7
  }, {
    artwork_id: 14,
    viewer_id: 6
  }, {
    artwork_id: 21,
    viewer_id: 1
  }, {
    artwork_id: 19,
    viewer_id: 3
  }, {
    artwork_id: 10,
    viewer_id: 2
  }, {
    artwork_id: 18,
    viewer_id: 5
  }, {
    artwork_id: 16,
    viewer_id: 8
  }, {
    artwork_id: 1,
    viewer_id: 3
  }, {
    artwork_id: 5,
    viewer_id: 4
  }, {
    artwork_id: 30,
    viewer_id: 2
  }, {
    artwork_id: 25,
    viewer_id: 1
  }, {
    artwork_id: 20,
    viewer_id: 7
  }, {
    artwork_id: 4,
    viewer_id: 4
  }, {
    artwork_id: 19,
    viewer_id: 8
  }, {
    artwork_id: 12,
    viewer_id: 6
  }, {
    artwork_id: 30,
    viewer_id: 5
  }, {
    artwork_id: 10,
    viewer_id: 8
  }, {
    artwork_id: 18,
    viewer_id: 8
  }, {
    artwork_id: 24,
    viewer_id: 5
  }, {
    artwork_id: 11,
    viewer_id: 8
  }, {
    artwork_id: 18,
    viewer_id: 5
  }, {
    artwork_id: 13,
    viewer_id: 2
  }, {
    artwork_id: 10,
    viewer_id: 2
  }, {
    artwork_id: 11,
    viewer_id: 3
  }, {
    artwork_id: 22,
    viewer_id: 8
  }, {
    artwork_id: 12,
    viewer_id: 7
  }, {
    artwork_id: 27,
    viewer_id: 5
  }, {
    artwork_id: 23,
    viewer_id: 2
  }, {
    artwork_id: 7,
    viewer_id: 5
  }, {
    artwork_id: 10,
    viewer_id: 8
  }, {
    artwork_id: 25,
    viewer_id: 8
  }, {
    artwork_id: 24,
    viewer_id: 2
  }, {
    artwork_id: 14,
    viewer_id: 7
  }, {
    artwork_id: 5,
    viewer_id: 3
  }, {
    artwork_id: 25,
    viewer_id: 5
  }, {
    artwork_id: 26,
    viewer_id: 3
  }, {
    artwork_id: 29,
    viewer_id: 2
  }, {
    artwork_id: 10,
    viewer_id: 3
  }, {
    artwork_id: 30,
    viewer_id: 2
  }, {
    artwork_id: 1,
    viewer_id: 3
  }, {
    artwork_id: 26,
    viewer_id: 5
  }, {
    artwork_id: 11,
    viewer_id: 3
  }, {
    artwork_id: 12,
    viewer_id: 7
  }, {
    artwork_id: 28,
    viewer_id: 2
  }, {
    artwork_id: 10,
    viewer_id: 4
  }, {
    artwork_id: 22,
    viewer_id: 4
  }, {
    artwork_id: 17,
    viewer_id: 1
  }, {
    artwork_id: 29,
    viewer_id: 8
  }, {
    artwork_id: 23,
    viewer_id: 3
  }, {
    artwork_id: 2,
    viewer_id: 2
  }, {
    artwork_id: 23,
    viewer_id: 3
  }, {
    artwork_id: 11,
    viewer_id: 5
  }, {
    artwork_id: 23,
    viewer_id: 5
  }, {
    artwork_id: 28,
    viewer_id: 1
  }, {
    artwork_id: 11,
    viewer_id: 7
  }, {
    artwork_id: 6,
    viewer_id: 8
  }, {
    artwork_id: 19,
    viewer_id: 4
  }, {
    artwork_id: 23,
    viewer_id: 4
  }, {
    artwork_id: 10,
    viewer_id: 4
  }, {
    artwork_id: 12,
    viewer_id: 8
  }, {
    artwork_id: 14,
    viewer_id: 5
  }, {
    artwork_id: 16,
    viewer_id: 2
  }, {
    artwork_id: 21,
    viewer_id: 5
  }, {
    artwork_id: 29,
    viewer_id: 5
  }, {
    artwork_id: 14,
    viewer_id: 1
  }, {
    artwork_id: 2,
    viewer_id: 2
  }, {
    artwork_id: 24,
    viewer_id: 2
  }, {
    artwork_id: 2,
    viewer_id: 4
  }, {
    artwork_id: 4,
    viewer_id: 2
  }, {
    artwork_id: 6,
    viewer_id: 7
  }, {
    artwork_id: 9,
    viewer_id: 6
  }, {
    artwork_id: 20,
    viewer_id: 1
  }, {
    artwork_id: 12,
    viewer_id: 8
  }, {
    artwork_id: 20,
    viewer_id: 4
  }, {
    artwork_id: 22,
    viewer_id: 5
  }, {
    artwork_id: 14,
    viewer_id: 5
  }, {
    artwork_id: 11,
    viewer_id: 1
  }, {
    artwork_id: 12,
    viewer_id: 2
  }, {
    artwork_id: 27,
    viewer_id: 4
  }, {
    artwork_id: 9,
    viewer_id: 4
  }, {
    artwork_id: 1,
    viewer_id: 7
  }, {
    artwork_id: 4,
    viewer_id: 6
  }, {
    artwork_id: 23,
    viewer_id: 2
  }, {
    artwork_id: 27,
    viewer_id: 2
}])